In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

 Tensors : Tensors are a datastructure to store numeric values in multidimensional space

TENSORS CAN HAVE MULTIPLE DIMENSIONS BASED ON THE SQUARE BRACKETS





In [ ]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor(
    [
        [
          [1,2],
          [3,4]
        ],
        [
          [6,7],
          [9,8]
          ]
        ])
matrix

tensor([[[1, 2],
         [3, 4]],

        [[6, 7],
         [9, 8]]])

In [ ]:
matrix.ndim

3

In [ ]:
matrix.shape


torch.Size([2, 2, 2])

#Random Tensor

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1883, 0.7544, 0.7718, 0.5518],
        [0.8553, 0.1605, 0.2735, 0.8635],
        [0.2662, 0.5356, 0.9655, 0.4806]])

Data Type and Changing Data Type
(TypeCasting)

In [ ]:
dtype_tensor =torch.tensor([3.0,6.0,9.1],
                           dtype =None,
                           device = None,
                           requires_grad= False)
dtype_tensor

tensor([3.0000, 6.0000, 9.1000])

In [ ]:
int_32_tensor = dtype_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
print(f"Tensor is on device : {int_32_tensor.device}")
print(f"Tensor is of the shape : {int_32_tensor.shape}")
print(f"Tensor is of type :{int_32_tensor.dtype}")

Tensor is on device : cpu
Tensor is of the shape : torch.Size([3])
Tensor is of type :torch.int32


# Tensor have can operated on addition, multiplication, division and subtraction

 Operation with Constants

In [ ]:
tensor =torch.tensor([1,2,3])
print(tensor)
print(f"Tensor + 10 is : {tensor+10}")
print(torch.add(tensor,5))
print(f"Tensor * 10 is : {tensor * 10}")
print(torch.mul(tensor,5))
print(f"Tensor / 10 is : {tensor/10}")
print(torch.div(tensor,5))
print(f"Tensor - 10 is : {tensor-10}")
print(torch.sub(tensor,5))

tensor([1, 2, 3])
Tensor + 10 is : tensor([11, 12, 13])
tensor([6, 7, 8])
Tensor * 10 is : tensor([10, 20, 30])
tensor([ 5, 10, 15])
Tensor / 10 is : tensor([0.1000, 0.2000, 0.3000])
tensor([0.2000, 0.4000, 0.6000])
Tensor - 10 is : tensor([-9, -8, -7])
tensor([-4, -3, -2])


Operation with other Tensors

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor,tensor)

tensor([1, 4, 9])

1. Torch.mul is multiplication and is not the same as matrix multiplication

2. Torch.mul is faster than for loops as it is vectorized




In [ ]:
tensorA= torch.tensor([[2,4],
                      [7,3],
                      [8,2]])
tensorA


tensor([[2, 4],
        [7, 3],
        [8, 2]])

In [ ]:
tensorB = torch.tensor([[5,1],
                      [6,3],
                      [4,7]])
tensorB

tensor([[5, 1],
        [6, 3],
        [4, 7]])

In [ ]:
#transposing a tensor
tensorB_t = tensorB.T
tensorB_t

tensor([[5, 6, 4],
        [1, 3, 7]])

MATRIX MULTIPLICATION
torch.matmul is the same as torch.mm

In [ ]:
torch.matmul(tensorA,tensorB_t)

tensor([[14, 24, 36],
        [38, 51, 49],
        [42, 54, 46]])

In [ ]:
torch.mm(tensorA,tensorB_t)

tensor([[14, 24, 36],
        [38, 51, 49],
        [42, 54, 46]])

# Statistics/Aggregation of Tensors

In [ ]:
x= torch.arange(4,60,12)
x

tensor([ 4, 16, 28, 40, 52])

In [ ]:
x.min(), torch.min(x)

(tensor(4), tensor(4))

In [ ]:
torch.max(x), x.max()

(tensor(52), tensor(52))

In [ ]:
torch.sum(x), x.sum()

(tensor(140), tensor(140))

#Mean only works with float type values tensors

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(28.), tensor(28.))

Finding the position of min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(4)

#Reshaping Squeezing and Unsqueezing
*   Reshaping : Reshapes an array
*   View: Views input tensor
*   Squeezing: Removes a `1` dimension from a tensor
*   Unsqueezing : Adds a `1` dimension to a target vector
*   Stacking : Stacks a tensor on top or side by side (increase dimensions)
*  Permute: Returns a view of input with dimensions permuted in a certain way









In [ ]:
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
#Add a dimension
x_reshaped = x.reshape(1,12)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
#Add a dimension
# x_reshaped = x.reshape(12,1)
# x_reshaped, x_reshaped.shape

In [ ]:
#Note you cannot add or remove elements so a 12 element tensor can be reshaoed to (3,4)(2,6),(1,12) and similar only
# x_reshaped = x.reshape(3,4)
# x_reshaped, x_reshaped.shape

In [ ]:
z= x.view(1,12)
z,x,z.shape,x.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([1, 12]),
 torch.Size([12]))

In [ ]:
#z and x share the same memory changing x will change z and vice versa
z[:,0]=1
z,x

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [ ]:
#Stacking
#vstack dim =0
#hstack dim =1
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
#Squeeze
x_reshaped.squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x_reshaped.unsqueeze(dim=1), x_reshaped.ndim, x_reshaped.shape


(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]]),
 2,
 torch.Size([1, 12]))

In [ ]:
#PERMUTE
x_original = torch.rand(size=(224,224,3))

x_original.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x_original[0,0,0]=3243
x_original[0,0,0], x_permuted[0,0,0]

(tensor(3243.), tensor(3243.))

#Indexing tensors

In [ ]:
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

Use : to select all values [n,:,m] is different from [n][:][m]

In [ ]:
x[0][:][2] , x[0,:,2]

(tensor([7, 8, 9]), tensor([3, 6, 9]))

#NUMPY

convert numpy to pytorch
torch.from_numpy(ndarray)

* convert pytorch to numpy
* torch.Tensor.numpy.()




In [ ]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) #as default is float 64
array, tensor , tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
#changing array memory
array = array+1
tensor , array
#does not share same memory

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Also does not share memory


In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])